steps:
  # Step 1: Build the container image and tag it for Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'
    - '.'

  # Step 2: Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'

# The 'options' block should be at the top level, like 'steps'
options:
  logging: CLOUD_LOGGING_ONLY

# Define the values for your variables here
substitutions:
  _LOCATION: 'us-central1'
  _REPOSITORY: 'mudblazor2'
  _IMAGE: 'my-image'
  _TAG: 'latest'
